### ISSUE TITLE
Issues from the old repo

### ISSUE THREAD

**Issue by Zren** [Zren/plasma-applet-todolist#1]
* [ ] [Akonadi/Kontact/PIM Integration](https://github.com/Zren/plasma-applets/issues/130)
* [ ] [Filter Items](https://github.com/Zren/plasma-applets/issues/128)
* [ ] [Counter overlay is very big, even overlapping other things in the panel, when panel is tall](https://github.com/Zren/plasma-applets/issues/122)

* [x] [Add ctrl+Return shortcut to mark item as complete](https://github.com/Zren/plasma-applets/pull/117)
* [ ] [Undo and Ctrl+Z keyboard shortcut?](https://github.com/Zren/plasma-applets/issues/108)
* [ ] [Option to show/hide complete tasks](https://github.com/Zren/plasma-applets/issues/106)
* [ ] [Text larger than box](https://github.com/Zren/plasma-applets/issues/102)
* [x] [Todo List error on KDE Plasma 5.10.5](https://github.com/Zren/plasma-applets/issues/100)
* [ ] [TodoList is not updated if storage file is updated](https://github.com/Zren/plasma-applets/issues/82)

**Comment by kikadf** [comment]
This lives yet: [No icon display](https://github.com/Zren/plasma-applets/issues/32)
I use breeze theme with oxygen icons.

**Comment by Zren** [comment]
The oxygen icon set does not have a "view-list" icon, nor a "view-list-symbolic" icon. Nor does it depend on the Breeze icon set. It hasn't been updated in 3 years.

https://github.com/KDE/oxygen-icons/find/master

Either edit my widget's code to use a valid icon, or modfiy the Oxygen icon theme to inherit Breeze.

To modify my widget, go to `~/.local/share/plasma/plasmoids/com.github.zren.todolist/contents/ui/` and open `main.qml`. Inside the file, you'll see an `IconItem` inside the `Plasmoid.compactRepresentation` [on line 48](https://github.com/Zren/plasma-applet-todolist/blob/master/package/contents/ui/main.qml#L48). Change the icon's `source: "view-list-symbolic"` to `source: "format-list-unordered"` which is a valid icon in the Oxygen icon set.

If you wish to edit the Oxygen icon set, edit `/usr/share/icons/oxygen/index.theme` to `inherit=breeze,hicolor` [on this line](https://github.com/KDE/oxygen-icons/blob/master/index.theme#L94) like the [Papyrus icon theme does](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/index.theme#L4).

And no, I will not change the icon to "format-list-unordered" since it looks bad in Breeze (the default appearance most users will see), and it's not in Adwaita which means it will not be in any Gtk icon theme.

![2018-12-04___13-14-17](https://user-images.githubusercontent.com/416367/49463545-b4944000-f7c6-11e8-9902-1a80092fc6b2.png)

I don't see a way to easily hardcode that icon name for the oxygen them since the current icon theme name doesn't appear to be exposed anywhere for QML code to read.

**Comment by kikadf** [comment]
Ok, thanks a lot. I understand the problem.

**Comment by anoopv511** [comment]
Is the [undo](https://github.com/Zren/plasma-applets/issues/108#issue-268841201) feature required?

**Comment by digitalethics** [comment]
@Zren What is the plan moving forward with issues from the old repo? Would you prefer some of these to be raised again here to start out fresh or to comment on the old issues?
